#!/usr/bin/env node
const fs = require('fs-extra')
const jsonFile = require('edit-json-file')
let ruleList=require('./rule')

let file=jsonFile(`${__dirname}/karabiner.json`)
let rules=file.get('profiles.0.complex_modifications.rules')
rules=rules.filter(v=>!ruleList.find(w=>w.description===v.description))
rules=rules.concat(ruleList)
file.set('profiles.0.complex_modifications.rules',rules)

fs.copySync(`${__dirname}/karabiner.json`, `${__dirname}/back/karabiner-${new Date().toISOString()}.json`)
file.save()
require('child_process').execSync('osacompile -l JavaScript -x -o key key.js')
require('child_process').execSync('osacompile -l JavaScript -x -o karabinerSuperCall karabinerSuperCall.js')
console.log(`'ok': `, 'ok')
